package ffc.v3.healthservice

import ffc.entity.healthcare.CommunityServiceType

interface CommunityServices {

    fun all(res: (List<CommunityServiceType>, Throwable?) -> Unit)
}

internal fun communityServices(): CommunityServices = MockCommunityService()

private class MockCommunityService : CommunityServices {

    val communityServices = listOf(
        CommunityServiceType("1A000", "เยี่ยมผู้ป่วยโรคความดันโลหิตสูง"),
        CommunityServiceType("1A001", "เยี่ยมผู้ป่วยโรคเบาหวาน"),
        CommunityServiceType("1A002", "เยี่ยมผู้ป่วยโรคมะเร็ง"),
        CommunityServiceType("1A003", "เยี่ยมผู้ป่วยโรคระบบทางเดินหายใจ"),
        CommunityServiceType("1A004", "เยี่ยมผู้ป่วยโรคสมองเสื่อม"),
        CommunityServiceType("1A005", "เยี่ยมผู้ป่วยโรคหลอดเลือดสมอง"),
        CommunityServiceType("1A008", "เยี่ยมผู้ป่วยโรคเรื้อรังอื่น ๆ"),
        CommunityServiceType("1A009", "เยี่ยมผู้ป่วยโรคเรื้อรังที่ไม่ระบุรายละเอียด"),
        CommunityServiceType("1A010", "เยี่ยมผู้ป่วยโรคไข้เลือดออก"),
        CommunityServiceType("1A011", "เยี่ยมผู้ป่วยโรคอุจจาระร่วง"),
        CommunityServiceType("1A012", "เยี่ยมผู้ป่วยโรคไข้หวัดใหญ่ 2009"),
        CommunityServiceType("1A013", "เยี่ยมผู้ป่วยโรคไข้หวัดใหญ่อื่นๆ หรือไม่ระบุรายละเอียด"),
        CommunityServiceType("1A014", "เยี่ยมผู้ป่วยโรควัณโรค"),
        CommunityServiceType("1A015", "เยี่ยมผู้ป่วยโรคกามโรค/สัมผัสกามโรค"),
        CommunityServiceType("1A016", "เยี่ยมผู้ป่วยโรคเอดส์"),
        CommunityServiceType("1A018", "เยี่ยมผู้ป่วยโรคติดต่ออื่น ๆ"),
        CommunityServiceType("1A019", "เยี่ยมผู้ป่วยโรคติดต่อที่ไม่ระบุรายละเอียด"),
        CommunityServiceType("1A020", "เยี่ยมผู้ป่วยโรคจิต"),
        CommunityServiceType("1A021", "เยี่ยมผู้ป่วยโรควิตกกังวล"),
        CommunityServiceType("1A022", "เยี่ยมผู้ป่วยโรคซึมเศร้า"),
        CommunityServiceType("1A023", "เยี่ยมผู้ป่วยโรคปัญญาอ่อน"),
        CommunityServiceType("1A024", "เยี่ยมผู้ป่วยโรคลมชัก"),
        CommunityServiceType("1A025", "เยี่ยมผู้พยายามฆ่าตัวตาย"),
        CommunityServiceType("1A028", "เยี่ยมผู้ป่วยโรคจิตและปัญหาสุขภาพจิตอื่นๆ"),
        CommunityServiceType("1A029", "เยี่ยมผู้ป่วยโรคจิตและปัญหาสุขภาพจิต ไม่ระบุรายละเอียด"),
        CommunityServiceType("1A030", "เยี่ยมผู้ป่วยที่ได้รับบาดเจ็บจากอุบัติเหตุ"),
        CommunityServiceType("1A031", "เยี่ยมผู้ป่วยที่ได้รับบาดเจ็บจากการถูกทำร้ายโดยคน"),
        CommunityServiceType("1A032", "เยี่ยมผู้ป่วยที่ได้รับบาดเจ็บจากการถูกทำร้ายโดยสัตว์"),
        CommunityServiceType("1A038", "เยี่ยมผู้ป่วยที่ได้รับบาดเจ็บจากสาเหตุภายนอกอื่น ๆ"),
        CommunityServiceType("1A039", "เยี่ยมผู้ป่วยที่ได้รับบาดเจ็บจากสาเหตุภายนอกที่ไม่ระบุรายละเอียด"),
        CommunityServiceType("1A10", "เยี่ยมผู้ป่วยหลังผ่าตัด"),
        CommunityServiceType("1A11", "เยี่ยมผู้ป่วยที่มีใบติดตามจากโรงพยาบาล"),
        CommunityServiceType("1A12", "เยี่ยมผู้ป่วยที่ต้องการดูแลอย่างต่อเนื่องจากโรงพยาบาล"),
        CommunityServiceType("1A13", "เยี่ยมติดตามผู้ป่วยขาดนัด"),
        CommunityServiceType("1A14", "เยี่ยมผู้ป่วยหลังจากรับ/ส่งต่อ (refer) จากโรงพยาบาล"),
        CommunityServiceType("1A18", "เยี่ยมผู้ป่วยหลังได้รับการรักษาอื่นๆ"),
        CommunityServiceType("1A19", "เยี่ยมผู้ป่วยหลังได้รับการรักษา  ไม่ระบุรายละเอียด"),
        CommunityServiceType("1A200", "เยี่ยมหญิงตั้งครรภ์แรก"),
        CommunityServiceType("1A201", "เยี่ยมหญิงตั้งครรภ์น้ำหนักน้อยกว่าเกณฑ์"),
        CommunityServiceType("1A202", "เยี่ยมหญิงตั้งครรภ์ที่มีภาวะเสี่ยง"),
        CommunityServiceType("1A203", "เยี่ยมหญิงตั้งครรภ์ที่แยกทางกับสามี"),
        CommunityServiceType("1A208", "เยี่ยมหญิงตั้งครรภ์กิจกรรมอื่นๆ"),
        CommunityServiceType("1A209", "เยี่ยมหญิงตั้งครรภ์  ไม่ระบุรายละเอียด"),
        CommunityServiceType("1A210", "เยี่ยมหญิงหลังคลอด ครั้งที่ 1 (1-2 สัปดาห์)  ที่ไม่มีภาวะผิดปกติ"),
        CommunityServiceType("1A211", "เยี่ยมหญิงหลังคลอด ครั้งที่ 1 (1-2 สัปดาห์)  ที่มีภาวะผิดปกติ"),
        CommunityServiceType("1A212", "เยี่ยมหญิงหลังคลอด ครั้งที่ 1 (1-2 สัปดาห์)  ไม่ระบุรายละเอียด"),
        CommunityServiceType("1A213", "เยี่ยมหญิงหลังคลอด ครั้งที่ 2 (4-6 สัปดาห์) ที่ไม่มีภาวะผิดปกติ"),
        CommunityServiceType("1A214", "เยี่ยมหญิงหลังคลอด ครั้งที่ 2 (4-6 สัปดาห์)  ที่มีภาวะผิดปกติ"),
        CommunityServiceType("1A215", "เยี่ยมหญิงหลังคลอด ครั้งที่ 2 (4-6 สัปดาห์)  ไม่ระบุรายละเอียด"),
        CommunityServiceType("1A216", "เยี่ยมหญิงหลังคลอด ครั้งอื่น  ที่ไม่มีภาวะผิดปกติ"),
        CommunityServiceType("1A217", "เยี่ยมหญิงหลังคลอด ครั้งอื่น  ที่มีภาวะผิดปกติ"),
        CommunityServiceType("1A218", "เยี่ยมหญิงหลังคลอด ครั้งอื่น  ไม่ระบุรายละเอียด"),
        CommunityServiceType("1A219", "เยี่ยมหญิงหลังคลอด  ไม่ระบุรายละเอียด"),
        CommunityServiceType("1A220", "เยี่ยมทารกแรกเกิด ครั้งที่ 1 (1-2 สัปดาห์)  ที่ไม่มีภาวะผิดปกติ"),
        CommunityServiceType("1A221", "เยี่ยมทารกแรกเกิด ครั้งที่ 1 (1-2 สัปดาห์)  ที่มีภาวะผิดปกติ"),
        CommunityServiceType("1A222", "เยี่ยมทารกแรกเกิด ครั้งที่ 1 (1-2 สัปดาห์)  ไม่ระบุรายละเอียด"),
        CommunityServiceType("1A223", "เยี่ยมทารกแรกเกิด ครั้งที่ 2 (4-6 สัปดาห์)"),
        CommunityServiceType("1A224", "เยี่ยมทารกแรกเกิด ครั้งที่ 2 (4-6 สัปดาห์)  ที่มีภาวะผิดปกติ"),
        CommunityServiceType("1A225", "เยี่ยมทารกแรกเกิด ครั้งที่ 2 (4-6 สัปดาห์)  ไม่ระบุรายละเอียด"),
        CommunityServiceType("1A226", "เยี่ยมทารกแรกเกิด ครั้งอื่น  ที่ไม่มีภาวะผิดปกติ"),
        CommunityServiceType("1A227", "เยี่ยมทารกแรกเกิด ครั้งอื่น  ที่มีภาวะผิดปกติ"),
        CommunityServiceType("1A228", "เยี่ยมทารกแรกเกิด ครั้งอื่น  ไม่ระบุรายละเอียด"),
        CommunityServiceType("1A229", "เยี่ยมทารกแรกเกิด ไม่ระบุรายละเอียด"),
        CommunityServiceType("1A30", "เยี่ยมผู้พิการทางการมองเห็น"),
        CommunityServiceType("1A31", "เยี่ยมผู้พิการทางการได้ยินหรือสื่อความหมาย"),
        CommunityServiceType("1A32", "เยี่ยมผู้พิการทางการเคลื่อนไหวหรือทางร่างกาย"),
        CommunityServiceType("1A33", "เยี่ยมผู้พิการทางจิตใจหรือพฤติกรรม หรือออทิสติก"),
        CommunityServiceType("1A34", "เยี่ยมผู้พิการทางสติปัญญา"),
        CommunityServiceType("1A35", "เยี่ยมผู้พิการทางการเรียนรู้"),
        CommunityServiceType("1A39", "เยี่ยมผู้ที่ความพิการยังไม่ได้รับการวินิจฉัยยืนยัน"),
        CommunityServiceType("1A400", "เยี่ยมเด็กอายุ 0 – 5 ปี ขาดอาหาร"),
        CommunityServiceType("1A401", "เยี่ยมเด็กอายุ 0 – 5 ปี  อ้วน"),
        CommunityServiceType("1A402", "เยี่ยมเด็กอายุ 0 – 5 ปี กลุ่มเสี่ยง(ค่อนข้างเตี้ย ค่อนข้างผอม น้ำหนักค่อนข้างน้อย ท้วม)"),
        CommunityServiceType("1A403", "เยี่ยมเด็กอายุ 0 – 5 ปี ที่มีการเจริญเติบโตดีแต่แนวโน้มการเจริญเติบโตไม่ดี"),
        CommunityServiceType("1A404", "เยี่ยมเด็กอายุ 0 – 5 ปี เพื่อติดตามพัฒนาการเด็กที่บกพร่อง / พัฒนาการไม่สมวัย"),
        CommunityServiceType("1A405", "เยี่ยมเด็กอายุ 0 – 5 ปี เพื่อติดตามเด็กที่มีโรคประจำตัว/ โรคร้ายแรง/ โรคที่ต้องเฝ้าระวัง"),
        CommunityServiceType("1A406", "เยี่ยมเด็กอายุ 0 – 5 ปี เพื่อติดตามเด็กให้ได้รับวัคซีนครบตามเกณฑ์/ เด็กขาดการรับวัคซีนตามนัด"),
        CommunityServiceType("1A407", "เยี่ยมเด็กอายุ 0 – 5 ปี เพื่อแนะนำผู้ปกครอง เรื่อง การแปรงฟันที่ถูกต้อง ด้วยยาสีฟันผสมฟลูออไรด์"),
        CommunityServiceType("1A408", "เยี่ยมเด็กอายุ 0 – 5 ปี กิจกรรมการให้บริการอื่น"),
        CommunityServiceType("1A409", "เยี่ยมเด็กอายุ 0 – 5 ปี  ไม่ระบุกิจกรรม"),
        CommunityServiceType("1A410", "เยี่ยมเด็กอายุ 6 - 18 ปี ขาดอาหาร"),
        CommunityServiceType("1A411", "เยี่ยมเด็กอายุ 6 - 18 ปี อ้วน"),
        CommunityServiceType("1A412", "เยี่ยมเด็กอายุ 6 - 18 ปี อยู่ในกลุ่มเสี่ยง (ค่อนข้างเตี้ย ค่อนข้างผอม น้ำหนักค่อนข้างน้อย ท้วม)"),
        CommunityServiceType("1A413", "เยี่ยมเด็กอายุ 6 - 18 ปี ที่มีการเจริญเติบโตดีแต่แนวโน้มการเจริญเติบโตไม่ดี"),
        CommunityServiceType("1A418", "เยี่ยมเด็กอายุ 6 - 18 ปี กลุ่มอื่น"),
        CommunityServiceType("1A419", "เยี่ยมเด็กอายุ 6 – 18 ปี  ไม่ระบุรายละเอียด"),
        CommunityServiceType("1A420", "เยี่ยมกลุ่มวัยแรงงานเพื่อติดตามภาวะเสี่ยงในการทำงาน ด้านการเกษตร"),
        CommunityServiceType("1A421", "เยี่ยมกลุ่มวัยแรงงานเพื่อติดตามภาวะเสี่ยงในการทำงาน ในโรงงานอุตสาหกรรม"),
        CommunityServiceType("1A422", "เยี่ยมกลุ่มวัยแรงงานเพื่อติดตามภาวะเสี่ยงในการทำงานด้านอุตสาหกรรมในครัวเรือน"),
        CommunityServiceType("1A428", "เยี่ยมกลุ่มวัยแรงงานเพื่อติดตามภาวะเสี่ยงในการทำงานด้านอื่น ๆ"),
        CommunityServiceType("1A429", "เยี่ยมกลุ่มวัยแรงงาน  ไม่ระบุรายละเอียด"),
        CommunityServiceType("1A430", "เยี่ยมผู้สูงอายุที่อยู่เพียงลำพัง"),
        CommunityServiceType("1A431", "เยี่ยมผู้สูงอายุที่ไม่อยู่เพียงลำพัง"),
        CommunityServiceType("1A439", "เยี่ยมผู้สูงอายุ  ไม่ระบุรายละเอียด"),
        CommunityServiceType("1A50", "เยี่ยมผู้ประสบภัยพิบัติทางธรรมชาติ"),
        CommunityServiceType("1A51", "เยี่ยมผู้ประสบภัยพิบัติที่เกิดจากไฟ"),
        CommunityServiceType("1A52", "เยี่ยมผู้ประสบภัยพิบัติทางสงคราม"),
        CommunityServiceType("1A53", "เยี่ยมและเยียวยาผู้ประสบภัยพิบัติจากการเข้าแทรกแซงตามกฎหมาย"),
        CommunityServiceType("1A54", "เยี่ยมและเยียวยาผู้ประสบภัยพิบัติจากการก่อการร้าย/จลาจล"),
        CommunityServiceType("1A58", "เยี่ยมและเยียวยาผู้ประสบภัยพิบัติอื่น ๆ"),
        CommunityServiceType("1A59", "เยี่ยมและเยียวยาผู้ประสบภัยพิบัติที่ไม่ระบุรายละเอียด"),
        CommunityServiceType("1A90", "เยี่ยมบ้านประชาชนสุขภาพดีเพื่อกิจกรรมการให้บริการเฉพาะเรื่อง"),
        CommunityServiceType("1A99", "เยี่ยมบ้านประชาชนสุขภาพดีทั่วไป")
    )

    override fun all(res: (List<CommunityServiceType>, Throwable?) -> Unit) {
        res(communityServices, null)
    }
}

val notDefineCommunityService = CommunityServiceType("null", "NULL")
